import { Outfit, Rozha_One } from 'next/font/google';
import './globals.css';
import Header from '@/components/layout/header';
import Footer from '@/components/layout/footer';
import { Toaster } from '@/components/ui/sonner';

const outfit = Outfit({
  variable: '--font-outfit',
  subsets: ['latin']
});
const rozha = Rozha_One({
  variable: '--font-rozha-one',
  subsets: ['latin'],
  weight: ['400']
});

export const metadata = {
  title: 'Maison Diorra',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${outfit.variable} ${rozha.variable} font-outfit flex min-h-screen flex-col antialiased`}
      >
        <Header />
        <main className='flex-1'>{children}</main>
        <Toaster expand={true} position='top-center' richColors />
        <Footer />
      </body>
    </html>
  );
}
